### ISSUE TITLE
createdAt get same updated timestamp like updatedAt

### ISSUE THREAD

**Issue by Oliver-G** [clarkbw/loopback-ds-timestamp-mixin#1]
In case your update a model the createdAt property will get the same value like updatedAt but I think the createAt timestamp should not change. 

If you change the **should update bulk model updates at once** test to:

``` javascript
var createdAt1, createdAt2, updatedAt1, updatedAt2;
```

and add in callback of book creation 1:

``` javascript
createdAt1 = book.createdAt;
```

and in callback of book creation 2:

``` javascript
createdAt2 = book.createdAt;
```

and in books.foreach

``` javascript
assert.equal(createdAt1.getTime(), book.createdAt.getTime());
assert.equal(createdAt2.getTime(), book.createdAt.getTime());
```

The test fails because createAt timestamps have changed are not the same.

**Comment by clarkbw** [comment]
> and in books.foreach

In the `forEach` call createdAt1 and createdAt2 should be different timestamps one of which will match each book so you can't evaluate it within the loop.  I added a check similar to what you're asking for before hand so you can see that even after the updateAll call the createdAt values for (what is now) `book1` and `book2` remain the same.

**Comment by Oliver-G** [comment]
Hello clarkbw,

maybe the test run without an error but in real use it seems that 
`, defaultFn: 'now'` in line 15 of index.js updates the createdAt property every time `before save` is called:

``` javascript
  Model.defineProperty(createdAt, { type: Date, required : true, defaultFn: 'now' });
```

The value of createdAt will not change after removing `, defaultFn: 'now'`.
I'm really new on LoopBack so I'm not sure whether this behavior comes from the ModelBaseClass or loopback-datasource-juggler or loopback-connector-mysql.

**Comment by clarkbw** [comment]
I'm sorry, I'm just not able to replicate the issue you're seeing.  I even did a quick test in the [datasource-juggler](https://github.com/strongloop/loopback-datasource-juggler/blob/master/test/manipulation.test.js#L880) module and can't see how this is happening in the higher level.  I have to believe this is something with your code or configuration.

**Comment by clarkbw** [comment]
@Oliver-G This issue is closed but if you can create a pull request that makes the travis ci build fail in the way you describe I can investigate it.  I just can't seem to reproduce what you're seeing.

**Comment by brainet** [comment]
Same problem for me. The test run without error,and I tested with loopback-datasource-juggler. It's looks like some package influenced it. I made an own mixins to defined property, with a default value. Then in `before save` hooks, the property always updated.
This question has been a torture for me for a few days.I don't know what caused it and how to resolve it.
:(

**Comment by clarkbw** [comment]
A previous issue that would show up like this was fixed.  In an upsert call the default values were being overwritten, see strongloop/loopback-datasource-juggler#616 for more information on that.  You need to be using v2.33.2 which has this update in it: https://github.com/strongloop/loopback-datasource-juggler/commit/b9e32bf8112171a154e1760af0ca91d546508dcb
