### ISSUE TITLE
Version in npm (2.1.1) does not work at all

### ISSUE THREAD

**Issue by gausie** [clarkbw/loopback-ds-timestamp-mixin#13]
Because of changes (index.js is ignored from mixin loading) the version in npm does not work. Can you update?

**Comment by clarkbw** [comment]
Yes, it looks a63ae8e44bdc48b0b6e3289a9c530cd644975834 has a change that ignores the `index.js` files now.  You can downgrade your loopback-boot to use v2.8.1 instead of v2.8.2

I can try to ship a quick update to fix this but I'm almost done the 3.0 version so I'd rather focus on that.

**Comment by clarkbw** [comment]
Pushed out version [v3.1.0](https://github.com/clarkbw/loopback-ds-timestamp-mixin/tree/v3.1.0) which should fix the issue.
