### ISSUE TITLE
loopback-datasource-juggler version clarification

### ISSUE THREAD

**Issue by josx** [clarkbw/loopback-ds-timestamp-mixin#15]
Reading doc you advice that loopback-datasource-juggler module must greater than version 2.23.0, but on package.json enforce the peerDependecies to >=2.33.2

Is there any problem to use it with loopback-datasource-juggler > 2.23.0 and < 2.33.2 ?

Just for the record, npm install log:

```
npm WARN peerDependencies The peer dependency loopback-datasource-juggler@>=2.33.2 included from loopback-ds-timestamp-mixin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm ERR! peerinvalid The package loopback-datasource-juggler does not satisfy its siblings' peerDependencies requirements!
```

**Comment by clarkbw** [comment]
I should update the README to clarify that.  2.33.2 has the fix for default values being overwritten on upsert calls.  See this pull request for more info strongloop/loopback-datasource-juggler#616

If that's not an issue for you then you can continue using 2.23.0

**Comment by josx** [comment]
Ok thanks for the info, will use it anyways with 2.23.0
