### ISSUE TITLE
Add documentation/implementation for mysql option

### ISSUE THREAD

**Issue by tngan** [clarkbw/loopback-ds-timestamp-mixin#19]
I have used mysql connector in loopback, and therefore I have to add options for mysql configuration.

```
{
  "name": "Widget",
  "properties": {
    "createdAt": {
      "type": "Date",
       "required": true,
       "length": null,
       "precision": null,
       "scale": null,
       "mysql": {
         "columnName": "created_at",
         "dataType": "datetime",
         "dataLength": null,
         "dataPrecision": null,
         "dataScale": null,
         "nullable": "N"
       }
  },
  "updatedAt": {
     "type": "Date",
     "required": true,
     "length": null,
     "precision": null,
     "scale": null,
     "mysql": {
       "columnName": "updated_at",
       "dataType": "timestamp",
       "dataLength": null,
       "dataPrecision": null,
       "dataScale": null,
       "nullable": "N"
     }
  }
  },
  "mixins": {
    "TimeStamp" : {
      "createdAt" : "createdAt",
      "updatedAt" : "updatedAt",
      "required" : false
    }
  }
}
```

The above configuration incurs `Unknown column "createdAt" in 'field list'`. The correct setting should be as follows, use the exact database column name instead of the loopback name mapping.

```
"mixins": {
    "TimeStamp" : {
      "createdAt" : "created_at",
      "updatedAt" : "updated_at",
      "required" : false
    }
  }
```

It would be better to clarify in README or force to use the loopback name mapping. I can make a pull request if it's preferable.

**Comment by clarkbw** [comment]
Interesting, I would have assumed that using the described name, `updatedAt` would have been the correct solution.  I'll make a note in the README the next chance I get to update things.

**Comment by clarkbw** [comment]
Added a note to the README, thanks for pointing this out!
