### ISSUE TITLE
Ability to manually set the date

### ISSUE THREAD

**Issue by mrfelton** [clarkbw/loopback-ds-timestamp-mixin#2]
When doing a data migration or import, it may be desirable to be able to set the created/updated date manually in order to retain legacy data. Could this mixin handle that or will it always set the dates regardless of wether they are set in the incoming data or not. How could the behaviour be bypassed?

**Comment by clarkbw** [comment]
If a `createdAt` is supplied it won't be overwritten by the default value the mixin uses.  However the `updatedAt` value is always overwritten on a save event.  We could create an inline option to allow for skipping the `updatedAt` save.
