### ISSUE TITLE
The timezone of timestamp doesn't match local one

### ISSUE THREAD

**Issue by jannyHou** [clarkbw/loopback-ds-timestamp-mixin#21]
I am trying to use this mixin to create timestamp for model, but The timezone of date doesn't match my local one.
Here is the simplified loopback app to reproduce the error:
https://github.com/jannyHou/loopback-sandbox/tree/simplify-app
- npm install
- open explorer
- use `POST/ Carts` to create an instance of `cart` model, leave `createdAt` and `updatedAt` blank
- use `GET/ Carts` to check the created instance, the timezone doesn't match local one.

My local timezone is UTC-05:00, but the `createdAt` and `updatedAt` I got are always 4 hours ahead.
Thank you in advance if anyone could take a look:)

**Comment by clarkbw** [comment]
Interesting, the code uses `new Date()` https://github.com/clarkbw/loopback-ds-timestamp-mixin/blob/master/es6/time-stamp.js#L26

Which can be used as a local or UTC date object, likely depends on the database juggler at that point.  I can dig around a little bit to see.

**Comment by clarkbw** [comment]
From a quick look I'd say https://github.com/strongloop/loopback-datasource-juggler passes this off to the connector to handle.  From the code it looks like the mysql connector is passing on the timezone information to the mysql module.  But that's all just a red herring.

Digging into the mysql module as pointed out in strongloop/loopback#2143 it looks like this is just how mysql works.  See https://github.com/felixge/node-mysql/issues/892#issuecomment-62322848 for more background.

The `dateStrings` solution seems to be the correct way to get the TZ you want without a lot of headache.  All the dates inside mysql are of the correct type and timestamp so you can still query and sort on them.  However when they return they won't be in the timezone you desire until you mess with them.
