### ISSUE TITLE
createdAt and updatedAt should not be required

### ISSUE THREAD

**Issue by cajoy** [clarkbw/loopback-ds-timestamp-mixin#3]
I add model hooks , for example "beforeCreate"

then before boot I add 

```
require('loopback-ds-timestamp-mixin')(app);

boot(app, options);
```

So Timestamp hook will be executed last in sequence.

And I am getting an error "updateAt" is undefined because save model before created/updated data generated

**Comment by clarkbw** [comment]
Can you point me to your project?  I'm not sure how you're getting this error.

**Comment by clarkbw** [comment]
@cajoy closing this out for now, we can open it back up if you can share more code so I can help you out.
