### ISSUE TITLE
loopback 3 alpha

### ISSUE THREAD

**Issue by chl03ks** [clarkbw/loopback-ds-timestamp-mixin#36]
Any plans to update the mixin with the current version of looback 3.4 alpha and if there so you need any help?

**Comment by clarkbw** [comment]
I haven't looked into it yet.  If you want to get started I can probably give you some guidance. 😄   But I won't have much time for the next couple weeks.  ✈️

**Comment by k1ng440** [comment]
Hello @clarkbw since 3.0 final version was released 2 days ago, can you please make it work with it?

Thanks

**Comment by ebarault** [comment]
using loopback 3, no problem so far with the mixin

**Comment by clarkbw** [comment]
> using loopback 3, no problem so far with the mixin

Ok, I'm going to close this for now as I don't know what the actionable items are.  Happy to reopen or open new issues with specific items.
