### ISSUE TITLE
Readme is wrong about silenceWarnings option

### ISSUE THREAD

**Issue by xibre** [clarkbw/loopback-ds-timestamp-mixin#58]
Hello. I've read the following thing from readme:

> This mixin uses console logs to warn you whenever something might need your attention. If you would prefer not to receive these warnings, you can disable them by setting the option silenceWarnings to false on a per model basis.

I was confused about why should we set this option to `false` because it's name says the opposite. I've checked the internals of the mixin and [this line](https://github.com/clarkbw/loopback-ds-timestamp-mixin/blob/master/es6/time-stamp.js#L5) reveals that warnings are printed if and only if silenceWarnings is falsy. So we need to set it to `true` to suppress the warnings, not `false`. Please update the readme.

Please also fix the example:

> In this example we change createdAt and updatedAt to createdOn and updatedOn, respectively. We also change the default required to false and set validateUpsert to true. We also disable console warnings with silenceWarnings.

```
...
"TimeStamp" : {
  "createdAt" : "createdOn",
  "updatedAt" : "updatedOn",
  "required" : false,
  "validateUpsert": true,
  "silenceWarnings": false         // <-- should be true
}
...
```

**Comment by clarkbw** [comment]
@xibre would you mind opening a PR to update the README as suggested?  You're right and I'm sorry you were confused but I haven't had the time to get this fixed.

**Comment by xibre** [comment]
@clarkbw done. Please take a look: https://github.com/clarkbw/loopback-ds-timestamp-mixin/pull/62.
